version: '3.3'
services:
  ai-codereview:
    container_name: ai-codereview
    image: python:3.12
    restart: always
    network_mode: "bridge"
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ..:/app/
    working_dir: /app
    #command: sh -c "pip install -i https://mirrors.sustech.edu.cn/pypi/web/simple/ -r requirements.txt && streamlit run ui.py --server.port=5002 --server.address=0.0.0.0"
    command: sh -c "pip install -i https://mirrors.sustech.edu.cn/pypi/web/simple/ -r requirements.txt && streamlit run ui.py --server.port=5002 --server.address=0.0.0.0 & pip install -i https://mirrors.sustech.edu.cn/pypi/web/simple/ -r requirements.txt &&  python api.py"